# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZuHS74EmQZkTVjWRM_gkRsJj_3g5GBaX
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

# --- 1. CẤU HÌNH TRANG ---
st.set_page_config(page_title="PCI 2025 - Logistics Optimization Dashboard", layout="wide")

st.title("📦 Phân tích Môi trường Kinh doanh (PCI 2025) phục vụ Logistics TMĐT")
st.markdown("""
Ứng dụng này sử dụng dữ liệu Chỉ số Năng lực cạnh tranh cấp tỉnh (PCI 2025) để hỗ trợ các doanh nghiệp
Thương mại điện tử ra quyết định lựa chọn địa điểm đặt Trung tâm Phân phối (Fulfillment Center).
Bạn có thể tự do điều chỉnh trọng số rủi ro để hệ thống tính toán và đề xuất địa điểm tối ưu.
""")

# --- 2. NẠP DỮ LIỆU ---
@st.cache_data
def load_data():
    # Đọc file CSV đã làm sạch từ Colab
    df = pd.read_csv('pci_2025_cleaned.csv')
    return df

df = load_data()

# --- 3. GIAO DIỆN ĐIỀU CHỈNH TRỌNG SỐ (DYNAMIC WEIGHTS) ---
st.sidebar.header("⚙️ Chiến lược Logistics của doanh nghiệp")
st.sidebar.markdown("Kéo thanh trượt để điều chỉnh mức độ ưu tiên của bạn đối với từng chỉ số (Tổng phải bằng 100%):")

# Thanh trượt cho 3 chỉ số
weight_hanh_chinh = st.sidebar.slider("1. Tốc độ thủ tục hành chính (%)", min_value=0, max_value=100, value=30, step=5)
weight_phi_an = st.sidebar.slider("2. Tối ưu Chi phí không chính thức (%)", min_value=0, max_value=100, value=40, step=5)
weight_phap_ly = st.sidebar.slider("3. An toàn Thiết chế pháp lý (%)", min_value=0, max_value=100, value=30, step=5)

total_weight = weight_hanh_chinh + weight_phi_an + weight_phap_ly

# Kiểm tra tổng trọng số
if total_weight != 100:
    st.sidebar.error(f"Tổng trọng số hiện tại là {total_weight}%. Vui lòng điều chỉnh lại cho đúng 100%.")
else:
    # --- 4. THUẬT TOÁN TÍNH ĐIỂM (DYNAMIC SCORING) ---
    # Tính điểm tổng hợp dựa trên trọng số do người dùng nhập (chuẩn hóa về thang thập phân)
    df['Điểm Tối ưu Logistics'] = (
        (df['Chi phí hành chính'] * (weight_hanh_chinh / 100)) +
        (df['Chi phí không chính thức'] * (weight_phi_an / 100)) +
        (df['Thiết chế pháp lý'] * (weight_phap_ly / 100))
    )

    # Làm tròn điểm
    df['Điểm Tối ưu Logistics'] = df['Điểm Tối ưu Logistics'].round(2)

    # Sắp xếp từ cao xuống thấp
    df_sorted = df.sort_values(by='Điểm Tối ưu Logistics', ascending=False).reset_index(drop=True)

    # --- 5. TRỰC QUAN HÓA DỮ LIỆU ---
    col1, col2 = st.columns([2, 1])

    with col1:
        st.subheader("📊 Bảng Xếp Hạng Đề Xuất (Top 10 Tỉnh/Thành)")
        # Lấy top 10
        top_10 = df_sorted.head(10)

        # Vẽ biểu đồ cột bằng Plotly
        fig = px.bar(
            top_10,
            x='Tỉnh/Thành phố',
            y='Điểm Tối ưu Logistics',
            color='Điểm Tối ưu Logistics',
            color_continuous_scale='Viridis',
            text='Điểm Tối ưu Logistics',
            title='Top 10 địa phương tối ưu chi phí và rủi ro chuỗi cung ứng'
        )
        fig.update_traces(textposition='outside')
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        st.subheader("🏆 Top 5 Đề Xuất Đặt Kho Bãi")
        st.dataframe(top_10[['Tỉnh/Thành phố', 'Điểm Tối ưu Logistics']].head(5), hide_index=True)

        st.info("💡 **Gợi ý:** Nếu bạn thay đổi trọng số ở thanh bên trái, danh sách này sẽ tự động cập nhật lại.")

    # Hiển thị toàn bộ dữ liệu chi tiết ở dưới cùng
    st.divider()
    st.subheader("📋 Bảng Dữ Liệu Chi Tiết (34 Tỉnh/Thành)")
    st.dataframe(df_sorted, use_container_width=True)